PALETTE = ["#1abc9c", "#2ecc71", "#3498db", "#9b59b6", "#34495e", "#16a085", "#27ae60", "#2980b9", "#8e44ad", "#2c3e50", "#f1c40f", "#e67e22", "#e74c3c", "#ecf0f1", "#95a5a6", "#f39c12", "#d35400", "#c0392b", "#bdc3c7", "#7f8c8d"]
STATS_COLS = {
  "symbol": "Symbol",
  "companyName": "Company Name",
  "marketcap": "Market Cap",
  "week52high": "52 Week High",
  "week52low": "52 Week Low",
  "week52highSplitAdjustOnly": "52 Week High Split Adjust Only",
  "week52lowSplitAdjustOnly": "52 Week Low Split Adjust Only",
  "week52change": "52 Week Change",
  "sharesOutstanding": "Outstanding Shares",
  "float": "Float",
  "avg10Volume": "Avg 10 Volume",
  "avg30Volume": "Avg 30 Volume",
  "day200MovingAvg": "200 Day MA",
  "day50MovingAvg": "50 Day MA",
  "employees": "Employees",
  "ttmEPS": "Trailing 12 Months EPS",
  "ttmDividendRate": "Trailing 12 Months Dividend Yield",
  "dividendYield": "Dividend Yield",
  "nextDividendDate": "Next Dividend Date",
  "exDividendDate": "Ex Dividend Date",
  "nextEarningsDate": "Next Earnings Date",
  "peRatio": "PE Ratio",
  "beta": "Beta",
  "maxChangePercent": "Max Change %",
  "year5ChangePercent": "5 Year Change %",
  "year2ChangePercent": "2 Year Change %",
  "year1ChangePercent": "1 Year Change %",
  "ytdChangePercent": "Year-to-date Change %",
  "month6ChangePercent": "6 Month Change %",
  "month3ChangePercent": "3 Month Change %",
  "month1ChangePercent": "1 Month Change %",
  "day30ChangePercent": "30 Day Change %",
  "day5ChangePercent": "5 Day Change %"
}

MARKET_COLS = {
  "avgTotalVolume": "Average Total Volume",
  "calculationPrice": "Calculation Price",
  "change": "Change",
  "changePercent": "Change %",
  "close": "Close",
  "closeSource": "Close Source",
  "closeTime": "Close Time",
  "companyName": "Company Name",
  "currency": "Currency",
  "delayedPrice": "Delayed Price",
  "delayedPriceTime": "Delayed Price Time",
  "extendedChange": "Extended Change",
  "extendedChangePercent": "Extended Change %",
  "extendedPrice": "Extended Price",
  "extendedPriceTime": "Extended Price Time",
  "high": "High",
  "highSource": "High Source",
  "highTime": "High Time",
  "iexAskPrice": "IEX Ask Price",
  "iexAskSize": "IEX Ask Size",
  "iexBidPrice": "IEX Bid Price",
  "iexBidSize": "IEX Bid Size",
  "iexClose": "IEX Close",
  "iexCloseTime": "IEX Close Time",
  "iexLastUpdated": "IEX Last Updated",
  "iexMarketPercent": "IEX Market Percent",
  "iexOpen": "IEX Open",
  "iexOpenTime": "IEX Open Time",
  "iexRealtimePrice": "IEX Realtime Price",
  "iexRealtimeSize": "IEX Realtime Size",
  "iexVolume": "IEX Volume",
  "lastTradeTime": "Last Trade Time",
  "latestPrice": "Latest Price",
  "latestSource": "Latest Source",
  "latestTime": "Latest Time",
  "latestUpdate": "Latest Update",
  "latestVolume": "Latest Volume",
  "low": "Low",
  "lowSource": "Low Source",
  "lowTime": "Low Time",
  "marketCap": "Market Cap",
  "oddLotDelayedPrice": "Odd Lot Delayed Price",
  "oddLotDelayedPriceTime": "Odd Lot Delayed Price Time",
  "open": "Open",
  "openTime": "Open Time",
  "openSource": "Open Source",
  "peRatio": "PE Ratio",
  "previousClose": "Previous Close",
  "previousVolume": "Previous Volume",
  "primaryExchange": "Primary Exchange",
  "symbol": "Symbol",
  "volume": "Volume",
  "week52High": "52 Week High",
  "week52Low": "52 Week Low",
  "ytdChange": "Year-to-date Change",
  "isUSMarketOpen": "Is US Market Open"
} 
